### ISSUE TITLE
watched-icon not properly displayed on firefox

### ISSUE THREAD

**Issue by Pheromir** [feederbox826/plugins#4]
Hello,

first: thanks for creating the plugin!

Unfortunately there seems to be an issue displaying the watched icon on firefox (126.0.1), causing the icon to be a transparent black bar at the top of the thumbnail:
![grafik](https://github.com/feederbox826/plugins/assets/13359741/710a8494-ad32-4940-bbe2-c9194126cc75)

while chromium based browsers (used MS Edge to test) correctly display the icon:
![grafik](https://github.com/feederbox826/plugins/assets/13359741/28ea4570-2e8d-4906-b25e-4eb54d4e552c)

maybe it's something easy to fix, but I'd understand if you won't support firefox (as video playback on chromium based browsers seem to be much better supported codec-wise) :D

**Comment by feederbox826** [comment]
I think I know exactly why and this has haunted me across projects https://caniuse.com/css-has

If you can confirm or deny your FireFox version (<121), that would help immensely, otherwise I gotta get creative haha

**Comment by Pheromir** [comment]
my firefox version is 126.0.1

**Comment by feederbox826** [comment]
I somehow can't seem to get it working even on chrome on v26 so I'm working on some updates heh

**Comment by feederbox826** [comment]
Turns out FF is much stricter with SVGs. Found a fix and tested it on latest ff https://stackoverflow.com/a/28783110
