### ISSUE TITLE
rebranding: issue when new title contains Stash and issue on subpages

### ISSUE THREAD

**Issue by AnonTester** [feederbox826/plugins#9]
Hi,
Thanks very much for this plugin, very useful!

This plugin seems to have a problem if the rebranding also contains the word 'Stash' i.e. with "Stash3D" the title can end up with "Stash3D3D3D" on refreshes. 
And it doesn't work right on some subpages, noticed for example on tag subpages like "/tags/319/scenes?sortby=date"

**Comment by feederbox826** [comment]
It does stupid text replacement just with `Stash` so having `Stash` in the name makes it freak out lol. Adding a regex to test that.

**Comment by feederbox826** [comment]
should be fixed in https://github.com/feederbox826/plugins/commit/49184971c01982dae010aeca5317bf283d5bf2af

0.3.0 should catch all edge cases of title change, let me know if it doesn't
